import type { NextPage } from 'next'
import Head from 'next/head'
import { NavLink } from '../components/navigation'
import homeBgGradient from '../assets/decoration/home-bg-gradient.png'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-5xl mx-auto mt-4 px-4">
        <nav className="flex items-center justify-between">
          <p className="text-slate-700">Rowin Hernandez</p>

          <div className="flex w-[500px] justify-between">
            <NavLink>Blog</NavLink>
            <NavLink>About</NavLink>
            <NavLink>Experience</NavLink>
            <NavLink>Projects</NavLink>
            <NavLink>Contact</NavLink>
          </div>

          <div className="text-slate-700">
            <button>Light / Dark</button>

            <button>Volume...</button>
          </div>
        </nav>

        <main className="border-x-2 px-2 border-black relative">
          <div className="absolute z-[-1] left-0 right-0 top-80 mx-2">
            <Image src={homeBgGradient} alt="" />
          </div>
          <header className="my-10">
            <h1 className="flex flex-col text-3xl sm:text-4xl md:text-5xl text-slate-800 items-start">
              Crafting things for...
              <span className="text-7xl sm:text-8xl md:text-9xl font-bold mt-4">
                Web
              </span>
              <span className="text-7xl sm:text-8xl md:text-9xl font-bold">
                Mobile
              </span>
              <span className="motion-safe:animate-gradient text-home-gradient text-7xl sm:text-8xl md:text-9xl font-bold text-transparent bg-clip-text">
                DevOps
              </span>
            </h1>
          </header>
        </main>
      </div>
    </>
  )
}

export default Home
